name: Question
description: Ask a question about using Solstice.
labels: ['help wanted']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your question
      description: A clear and concise description of what the problem is. Ex. I'm trying to[...]
    validations:
      required: true
  - type: textarea
    id: version-info
    attributes:
      label: Version Information
      description: If applicable, please provide the version of Solstice you are using.
      placeholder: Please provide your Solstice version (e.g. 2.2.0-beta.3) and your Android version.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about your question here.
